/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export enum Enabled {
    True = "true",
    False = "false",
}

export enum Status {
    Closed = "closed",
    Pinned = "pinned",
    PinnedGlobally = "pinned_globally",
    Archived = "archived",
    Visible = "visible",
}

export class UpdateTopicStatusRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled: Enabled;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: Status;

    /**
     * Only required for `pinned` and `pinned_globally`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "until" })
    until?: string;
}

export class UpdateTopicStatusRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=Api-Key" })
    apiKey: string;

    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=Api-Username" })
    apiUsername: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: UpdateTopicStatusRequestBody;
}

/**
 * topic updated
 */
export class UpdateTopicStatusResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "topic_status_update" })
    topicStatusUpdate?: string;
}

export class UpdateTopicStatusResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * topic updated
     */
    @SpeakeasyMetadata()
    object?: UpdateTopicStatusResponseBody;
}
